title: Guides by PixelGrade
email: contact@pixelgrade.com
description: 'Basic guides, components and standards for WordPress development'
url: 'http://127.0.0.1:4000'
twitter_username: pixelgrade
github_username: pixelgrade
gems:
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-feed
    - jemoji
latest_version: 1.3.2
sass:
    style: compressed
available_versions:
    - v1.3.2
exclude:
    - node_modules
    - README.md
    - LICENSE.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - Gruntfile.js
    - package.json
    - script
    - spec
navigation:
- text: View on GitHub
  url: https://github.com/pixelgrade/guides
- text: Contribute
  url: /contribute
- text: Stylesheets
  url: /stylesheets
- text: Scripts
  url: /scripts
- text: Theme
  url: /wp-theme
- text: Child Theme
  url: /child
- text: Components
  url: /components