title: Guides by PixelGrade
email: contact@pixelgrade.com
description: '– – –'
url: 'http://pixelgrade.github.io/guides/'
twitter_username: pixelgrade
github_username: pixelgrade
latest_version: 1.3.2
sass:
    style: compressed
available_versions:
    - v1.3.2
exclude:
    - node_modules
    - README.md
    - LICENSE.md
    - CNAME
    - Gemfile
    - Gemfile.lock
    - Gruntfile.js
    - package.json
    - script
    - spec
navigation:
- text: View on GitHub
  url: https://github.com/pixelgrade/guides
- text: Contribute
  url: /guides/contribute
- text: Stylesheets
  url: /guides/stylesheets
- text: Scripts
  url: /guides/scripts
- text: Theme
  url: /guides/wp-theme
- text: Child Theme
  url: /guides/child
- text: Components
  url: /guides/components